# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_certificate_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
