# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20170710_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
